# assignment day 3 

In [11]:
import numpy as np 
arr = np.arange(2,50,3).reshape(4,4)
print(arr)

[[ 2  5  8 11]
 [14 17 20 23]
 [26 29 32 35]
 [38 41 44 47]]


In [47]:
import numpy as np
lst1 =[]
lst2 =[]
print("Enter 5 element in 1st list")
for i in range(0,5):
    value = int(input())
    lst1.append(value)

print("Enter 5 element in 2st list")
for j in range(0,5):    
    ele = int(input())
    lst2.append(ele)
    
print("Array of list 1")
arr1 = np.array(lst1)
print(arr1)
print("Array of list 2")
arr2 = np.array(lst2)
print(arr2)

#adding two array
concate = np.concatenate((arr1,arr2))
print("Concatenated array is :")
print(concate)
#sorting array
sort_concate = np.sort(concate)
print("sorted array is :")
print(sort_concate)

Enter 5 element in 1st list
23
56
45
90
34
Enter 5 element in 2st list
22
45
11
44
78
Array of list 1
[23 56 45 90 34]
Array of list 2
[22 45 11 44 78]
Concatenated array is :
[23 56 45 90 34 22 45 11 44 78]
sorted array is :
[11 22 23 34 44 45 45 56 78 90]


In [56]:
import numpy as np
a = np.array([[3, 4, 5], [6, 7, 8],[9,10,11],[12,1,2]])
print(a)

# get number of rows in nd numpy array
numOfRows = a.shape[0]
print('Number of Rows : ', numOfRows)

# get number of columns in nD numpy array
numOfColumns = a.shape[1]
print('Number of Columns : ', numOfColumns)

print()
print('Total Number of elements in  Numpy array : ', a.shape[0] * a.shape[1])

print('Shape of numpy array : ', a.shape)
print('Total Number of elements in  Numpy array : ', np.size(a))

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12  1  2]]
Number of Rows :  4
Number of Columns :  3

Total Number of elements in  Numpy array :  12
Shape of numpy array :  (4, 3)
Total Number of elements in  Numpy array :  12


In [64]:
arr = np.array([1, 2, 3, 4, 5, 6])
print("shape of original vertor or 1d array ",arr.shape)
#with row_vector
arr2 = arr[np.newaxis, :]
print("2d array With .newaxis and row_vector", arr2.shape)
#with column-vector
col_vector = arr[:, np.newaxis]
print("2d array With .newaxis and column-vector",col_vector.shape)

#with expand_dims
arr3 = np.expand_dims(arr, axis=1)
print("2d array with .expand_dims",arr3.shape)

shape of original vertor or 1d array  (6,)
2d array With .newaxis and row_vector (1, 6)
2d array With .newaxis and column-vector (6, 1)
2d array with .expand_dims (6, 1)
