# assignment day 3 

In [2]:
import numpy as np 
arr = np.arange(2,50,3).reshape(4,4)
print(arr)

[[ 2  5  8 11]
 [14 17 20 23]
 [26 29 32 35]
 [38 41 44 47]]


In [3]:
import numpy as np
lst1 =[]
lst2 =[]
print("Enter 5 element in 1st list")
for i in range(0,5):
    value = int(input())
    lst1.append(value)

print("Enter 5 element in 2st list")
for j in range(0,5):    
    ele = int(input())
    lst2.append(ele)
    
print("Array of list 1")
arr1 = np.array(lst1)
print(arr1)
print("Array of list 2")
arr2 = np.array(lst2)
print(arr2)

#adding two array
concate = np.concatenate((arr1,arr2))
print("Concatenated array is :")
print(concate)
#sorting array
sort_concate = np.sort(concate)
print("sorted array is :")
print(sort_concate)

Enter 5 element in 1st list
23
44
65
88
66
Enter 5 element in 2st list
23
54
77
12
1
Array of list 1
[23 44 65 88 66]
Array of list 2
[23 54 77 12  1]
Concatenated array is :
[23 44 65 88 66 23 54 77 12  1]
sorted array is :
[ 1 12 23 23 44 54 65 66 77 88]


In [4]:
import numpy as np
a = np.array([[3, 4, 5], [6, 7, 8],[9,10,11],[12,1,2]])
print(a)

# get number of rows in nd numpy array
numOfRows = a.shape[0]
print('Number of Rows : ', numOfRows)

# get number of columns in nD numpy array
numOfColumns = a.shape[1]
print('Number of Columns : ', numOfColumns)

print()
print('Total Number of elements in  Numpy array : ', a.shape[0] * a.shape[1])

print('Shape of numpy array : ', a.shape)
print('Total Number of elements in  Numpy array : ', np.size(a))

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12  1  2]]
Number of Rows :  4
Number of Columns :  3

Total Number of elements in  Numpy array :  12
Shape of numpy array :  (4, 3)
Total Number of elements in  Numpy array :  12


In [5]:
arr = np.array([1, 2, 3, 4, 5, 6])
print("shape of original vertor or 1d array ",arr.shape)
#with row_vector
arr2 = arr[np.newaxis, :]
print("2d array With .newaxis and row_vector", arr2.shape)
#with column-vector
col_vector = arr[:, np.newaxis]
print("2d array With .newaxis and column-vector",col_vector.shape)

#with expand_dims
arr3 = np.expand_dims(arr, axis=1)
print("2d array with .expand_dims",arr3.shape)

shape of original vertor or 1d array  (6,)
2d array With .newaxis and row_vector (1, 6)
2d array With .newaxis and column-vector (6, 1)
2d array with .expand_dims (6, 1)


In [8]:
import numpy as np

my_array_1 = np.square([2,5,6,7,8,9,21,12,3,1,4])  # square of numpy array
my_array_2 = np.square([6,8,7,23,16,34,22,44])  # square of numpy array


print(" horizontally stacked : ", np.hstack((my_array_1, my_array_2)))

print("vertically stacked : ", np.hstack((my_array_1, my_array_2)))

 horizontally stacked :  [   4   25   36   49   64   81  441  144    9    1   16   36   64   49
  529  256 1156  484 1936]
vertically stacked :  [   4   25   36   49   64   81  441  144    9    1   16   36   64   49
  529  256 1156  484 1936]


In [6]:
import numpy as np

arr = np.array([2,5,6,4,7,5,2,2,2,4,2])

unique, counts = np.unique(arr, return_counts=True)
arr = np.asarray((unique, counts)).T
print(arr)

[[2 5]
 [4 2]
 [5 2]
 [6 1]
 [7 1]]
